CREATE TABLE accounts(
    id VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    document VARCHAR(16) NOT NULL UNIQUE,

    PRIMARY KEY(ID),
    CONSTRAINT FOREIGN KEY(user_id) REFERENCES  users(id)
)