version: '3'
services:
  db:
    image: mysql:latest  
    container_name: mysql-troca-facil  
    ports:
      - "3500:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: root123 
    volumes:
      - /caminho/local/para/dados/mysql:/var/lib/mysql  
  discovery:
    image: discovery:1.0
    environment:
      MYSQL_URL: jdbc:mysql://db:3312
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
    ports:
      - "8761:8761"
  
  gateway:
    image: gateway:1.0
    environment:
      MYSQL_URL: jdbc:mysql://db:3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
    ports:
      - "8052:8052"
    depends_on:
      - db
      - discovery

  ems:
    image: ems:1.0
    environment:
      MYSQL_URL: jdbc:mysql://db:3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
    ports:
      - "8055:8052"
    depends_on:
      - db
      - discovery
      - gateway

  authentication:
    image: authentication:1.0
    environment:
      MYSQL_URL: jdbc:mysql://db:3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
    ports:
      - "8051:8051"
    depends_on:
      - db
      - discovery
      - gateway

  principal:
    image: principal:1.0
    environment:
      DISCOVERY_SERVER: http://discovery:8761/eureka/
      MSG_EXIBIR: FUNCIONOU
    ports:
      - "3000:3000"
    depends_on:
      - db
      - discovery
      - gateway
